version: '3.8'

services:
  mssql:
    build: ./mssql
    container_name: mssql
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql_data:
